### ISSUE TITLE
How do you use kubespy when your cluster is running on AWS?

### ISSUE THREAD

**Issue by flybd5** [pulumi/kubespy#12]
I cannot see how to run this tool if the kubernetes is running in AWS. Also, what are the options for kind and type?

**Comment by hausdorff** [comment]
`kubespy` works any place you are using a [kubeconfig file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/). Usually this is at `~/.kube/config` or denoted with the environment variable `$KUBECONFIG`.

`kubespy` works with any group/version/kind supported by the API server. On recent versions of `kubectl` (which is what you should be running if you're using EKS), you'd use these commands to see available `kind` and `apiVersion`s:

```sh
kubectl api-resources # list available kinds
kubectl api-versions # list available apiVersions
```

LMK if I'm still missing something...

**Comment by flybd5** [comment]
Got it. Figured it out. Now have to figure out what it does and how to use
it.

**Comment by hausdorff** [comment]
Ha. Well, let us know if we can help. I'll close this issue as it seems it is resolved.
