### ISSUE TITLE
unable to read kubeconfig for multiple k8s clusters

### ISSUE THREAD

**Issue by karnatinaresh** [pulumi/kubespy#18]
---) kubespy changes v1 pod nginx
Unable to read kubectl config: invalid configuration: no configuration has been provided
Seeing this error messages i have multiple clusters and kubeconfig has multiple cluster config.

**Comment by hausdorff** [comment]
Under the cover's we're using kubernetes/client-go, so parsing a multi-cluster kubeconfig seems unlikely to be the issue. Based on what you've described, I'm guessing we actually can't find the kubeconfig file at all. When you run `echo $KUBECONFIG` what do you see?

**Comment by hausdorff** [comment]
@karnatinaresh Since I think I'm correct in my assessment, I'm going to go ahead and close this issue. If you think I'm wrong in my assessment please do re-open and let's talk.

**Comment by hausdorff** [comment]
Why do you believe this is an issue related to having multiple clusters?

**Comment by karnatinaresh** [comment]
Because when i am running kubespy with a single cluster config it is working.
I also tested the same on a different machine with minikube it is working.
