### ISSUE TITLE
Refactor kubespy into separate commands inside cmd directory

### ISSUE THREAD

**Issue by liftedkilt** [pulumi/kubespy#19]
Would you be interested in a PR to refactor kubespy into separate distinct commands? IMHO it will make it easier to extend kubespy without stuffing it all into main.go.

Let me know what you think.

**Comment by hausdorff** [comment]
@liftedkilt we would! Just a bit of background -- I wrote this tool to help me make gifs for our blog. It was very surprising to us when it took off. I didn't even set up CI! So in general, improvements are welcome. :)

**Comment by liftedkilt** [comment]
@hausdorff ,

Sure thing! I'm not entirely happy with how much duplication there is with the `consts` and the text format vars. I originally started refactoring all that out, but I didn't want to completely redo everything in a single PR.

I'm totally open to changes - just let me know how you want to proceed.

Thanks!

**Comment by hausdorff** [comment]
Also -- because the job of this tool is to provide advisory information to humans in a human-readable form, I'm not as worried about code quality as I am in, say, the official Pulumi Kubernetes provider, where correctness is utterly mission-critical. :)

**Comment by liftedkilt** [comment]
@hausdorff for sure - thanks for the cool tool, and sorry for the barrage of comments and PRs!
