### ISSUE TITLE
Hook up to CI

### ISSUE THREAD

**Issue by liftedkilt** [pulumi/kubespy#23]
It looks like pulumi/pulumi is using Travis for CI, so I assume we'll want to do the same here?

Obviously a full suite of unit tests would be nice, but maybe we should start with just a quick smoke check to make sure things build properly?

**Comment by hausdorff** [comment]
You're exactly right, we would have done this sooner, but I'm not an admin of the pulumi org, and had to get someone to click the button to enable travis. The button was clicked yesterday, so we can put the appropriate travis files in the repo and we should be good to go.
