### ISSUE TITLE
kubespy fails to build 

### ISSUE THREAD

**Issue by liftedkilt** [pulumi/kubespy#29]
We seem to be in dependency hell: https://travis-ci.com/pulumi/kubespy/builds/86373938#L1033

This relates to the discussion on #10

**Comment by liftedkilt** [comment]
Appears to be related to: https://github.com/golang/go/issues/27457

**Comment by hausdorff** [comment]
The positive side is that this is the exact sort of thing that's nice to find out when working on `pulumi/kubespy` instead of `pulumi/pulumi`. Looking now...

**Comment by hausdorff** [comment]
@liftedkilt BTW, the [Gopkg.lock file](https://github.com/pulumi/pulumi-kubernetes/blob/master/Gopkg.lock) inpulumi-kubernetes _should_ in principle solve the problem of deciding which versions of our dependencies we need. The question I don't have the answer for is: how does one express these with Go modules?
