### ISSUE TITLE
Stray characters when tracing Service

### ISSUE THREAD

**Issue by suda** [pulumi/kubespy#38]
<img width="811" alt="screenshot 2018-10-04 16 21 55" src="https://user-images.githubusercontent.com/25722/46493538-e9a90400-c810-11e8-952e-0971e114dd83.png">

You can see two characters left from the previous ["Waiting for service"](https://github.com/pulumi/kubespy/blob/master/cmd/trace.go#L76) message. The bug is upstream in `uilive` and even has a [PR open to fix this](https://github.com/gosuri/uilive/pull/12) but it has been over a year and the maintainer haven't commited anything since [23 Mar 2017](https://github.com/gosuri/uilive/commits/master). I see two fixes here:

* switch the package to use the [fork with the fix](https://github.com/mbrlabs/uilive/)
* add two spaces before the newline in [`Fprintf `](https://github.com/pulumi/kubespy/blob/master/print/print.go#L517) 😅

I would gladly do a PR with a fix, just let me know which one you'd prefer :)

**Comment by hausdorff** [comment]
@suda thanks for the offer! We will gladly take you up on it. I say we just move to the fork.
