### ISSUE TITLE
kubespy only outputs watching status

### ISSUE THREAD

**Issue by rakidu** [pulumi/kubespy#50]
I installed kubespy on y k8s master server. however when i run kubespy commands all i get is output watching status. nothing else.

**Comment by hausdorff** [comment]
@rakidu it is going to be very hard to respond to this issue without more context. :) What command did you run? What pods and services exist in your cluster?

**Comment by rakidu** [comment]
Hi 
I am using an ACS kubernetes cluster with 3 masters & 3 nodes.
Installed kubespy and running on one of the masters.

I ran kubespy trace & Kubespy status it only outputs watching status.
kubespy trace svc [namespace/]varnish5-sterile-active-service
Waiting for Service '[namespace/]varnish5-sterile-active-service'

When I run the same command as root user i am getting below error
kubespy trace svc [sce-dms-drupal/]varnish5-sterile-active-service
Unable to read kubectl config: invalid configuration: no configuration has been provided

Hope this helps

**Comment by hausdorff** [comment]
For the second error, it says it can't find your [kubeconfig file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/). We use the official Kubernetes Go client under the hood, so if it's saying that, it probably means it really doesn't exist.

For the first error, can you give me the _exact_ command you ran, and the _exact_ output when you `kubectl get` the object?

**Comment by rakidu** [comment]
kubespy trace svc [sce-dms-drupal/]varnish5-sterile-active-service
Waiting for Service '[sce-dms-drupal/]varnish5-sterile-active-service'

its getting struck here

**Comment by hausdorff** [comment]
I need the _exact_ command you ran (_i.e._, without the `[` and `]` characters), and _also_ the `kubectl get` output.

**Comment by leezen** [comment]
Closing stale issue
