### ISSUE TITLE
Server is unable to handle /v1, Kind=Statefulset

### ISSUE THREAD

**Issue by jkogut** [pulumi/kubespy#57]
Adding support for Kind=Statefulset would be much appreciated.

**Comment by lukehoban** [comment]
Could you share the complete output?  I believe Pulumi does support this, but sounds like you are deploying to a Kubernetes cluster which does not support it.

**Comment by jkogut** [comment]
For a given sts:
`$ kctl get sts
NAME   READY   AGE
nifi   3/3     36m
zk     3/3     52m
`

I was trying to use kubespy to get progress status
`$ kubespy status v1 statefulset zk
Server is unable to handle /v1, Kind=Statefulset
`

Kubectl version:
`$ kctl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

Searched with `ack-grep statefulset  .` through `kubespy` source code found nothing, therefore I guess it is not implemented.

 Also, implementing kubectl shortcuts like sts, svc would be very convenient, example:
`$ kubespy status v1 svc nginx`

**Comment by lblackstone** [comment]
The kind name is case sensitive, so you have to use
`kubespy status apps/v1 StatefulSet zk`.

Related #49

**Comment by jkogut** [comment]
ok, that was imho confusing:

**case sensitive:**
satefulset != StatefulSet

```
$ kubespy status apps/v1 statefulset nifi
Server is unable to handle apps/v1, Kind=Statefulset

$ kubespy status apps/v1 StatefulSet nifi
Watching status of apps/v1 StatefulSet nifi
```

**not case sensitive:**
deployment == Deployment
```
$ kubespy status apps/v1 deployment nifi-registry
Watching status of apps/v1 deployment nifi-registry

$ kubespy status apps/v1 Deployment nifi-registry
Watching status of apps/v1 Deployment nifi-registry
```
