### ISSUE TITLE
installing the plugin on google kubernates engine

### ISSUE THREAD

**Issue by SaralSaxena** [pulumi/kubespy#69]
I am using google Kubernetes engine, how can I install the same there, please advise

**Comment by lblackstone** [comment]
kubespy isn't a plugin; it's a client-side tool. It should work with whatever kubeconfig you have configured in your terminal. In other words, if you can connect to your GKE cluster with `kubectl`, then `kubespy` should work in the same terminal without further configuration.

**Comment by SaralSaxena** [comment]
Please advise the steps in detailed how to run the same in google Kubernetes engine

**Comment by hausdorff** [comment]
The readme provides detailed instructions for running kubespy. Please follow the instructions there.

You will see when you read the instructions that you don't run it inside GKE. It's a command line tool that is run locally.

Alex

Theory is the first term in the Taylor series of practice. -- Thomas M Cover (1992)
