### ISSUE TITLE
Make binary releases

### ISSUE THREAD

**Issue by surajssd** [pulumi/kubespy#7]
I understand that using `go get` it is easier to install this tool. But given the dependency this project pulls in the overhead of `go get` is too much. Because pulling in almost entire k8s goes over a gigabyte in code size.

It would be helpful for people who want to quickly try out the project to download the binary and use it.

**Comment by hausdorff** [comment]
Done: https://github.com/pulumi/kubespy/releases/tag/v0.3.0
