### ISSUE TITLE
Trace custom k8s resources?

### ISSUE THREAD

**Issue by s3rj1k** [pulumi/kubespy#79]
It is not directly obvious from docs can `kubespy` trace custom k8s resources and please provide example if it can.

**Comment by leezen** [comment]
This is already documented in the `README` https://github.com/pulumi/kubespy#features

**Comment by s3rj1k** [comment]
@leezen The reason that I asked, It did not work for me, so I wanted confirmation from a human that this does work.

Your answer sadly does not confirm anything.

**Comment by s3rj1k** [comment]
Please confirm that this is supported just by saying this. Thanks

**Comment by leezen** [comment]
Yes. Please file a bug with repro steps in the case where you were unable to get it to work.
