### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by kedare** [pulumi/kubespy#95]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, some deployments are not providing ARM64 images, which make using Kubespy not useable on ARM64 nodes. (AWS graviton for example)

### Affected area/feature

Usage is blocked as many containers will not start (image not found for arm64)

**Comment by mjeffryes** [comment]
That's a reasonably ask @kedare. It should be as straightforward as updating the [goreleaser config](https://github.com/pulumi/kubespy/blob/9d609e6be49386fe214499ce34fa8769efa206cc/.goreleaser.yml#L10) and cutting a new release.

**Comment by kedare** [comment]
Hello

Sorry actually I got confused, it does work fine on arm64 cluster,

Thank you and sorry for the noise 😅

**Comment by rquitales** [comment]
arm64 artifacts are now built from v0.6.3.
